#!/usr/bin/env python3
"""Run chief_agent.py for each prompt generated by generate_event_prompts."""

from __future__ import annotations

import json
import shlex
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROMPT_FILE = PROJECT_ROOT / "data" / "batch_prompts.txt"
CHIEF_SCRIPT = PROJECT_ROOT / "chief_agent.py"
HTML_DIR = PROJECT_ROOT / "results" / "html"


def safe_write(html_path: Path, content: str) -> Path:
    """Write HTML to unique path (no overwrite)."""
    base = html_path.stem
    suffix = html_path.suffix
    candidate = html_path
    counter = 1
    while candidate.exists():
        candidate = html_path.with_name(f"{base}_{counter}{suffix}")
        counter += 1
    candidate.write_text(content, encoding="utf-8")
    return candidate


def extract_html_path(output: str) -> str:
    """
    Best-effort extraction of HTML report path from chief_agent stdout.
    Supports:
    - JSON lines containing html_report_path (if any in the future)
    - Text lines like:
        "📄 HTML Report: /path/to/report.html"
        "📄 Batch HTML Report Generated: /path/to/report.html"
    """
    lines = output.splitlines()

    # 1) Look for explicit "HTML Report:" / "Batch HTML Report" lines (most reliable)
    for line in reversed(lines):
        if "HTML Report:" in line:
            return line.split("HTML Report:")[-1].strip()
        if "Batch HTML Report Generated:" in line:
            return line.split("Batch HTML Report Generated:")[-1].strip()
        if "Batch HTML Report:" in line:
            return line.split("Batch HTML Report:")[-1].strip()

    # 2) Fallback: try JSON lines with html_report_path (future‑proof)
    for line in reversed(lines):
        if "html_report_path" in line or "html_report" in line:
            try:
                data = json.loads(line)
            except json.JSONDecodeError:
                continue
            report = data.get("report_result") or data.get("analysis_report") or {}
            path = report.get("html_report_path")
            if path:
                return path

    # 3) Last resort: pick the last existing *.html path that looks like a file path
    for line in reversed(lines):
        if ".html" in line:
            candidate = line.split()[-1].strip()
            if candidate.endswith(".html"):
                return candidate

    return ""


def run_prompt(event_name: str, prompt: str):
    cmd = [
        "python",
        str(CHIEF_SCRIPT),
        "--user-input",
        prompt,
    ]
    print(f"\n=== Running {event_name} ===")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"{event_name}: FAILED ({result.stderr.strip()})")
        return

    # Try to extract HTML report path from stdout
    html_path = extract_html_path(result.stdout)

    if not html_path or not Path(html_path).exists():
        print(f"{event_name}: SUCCESS but report path not found")
        return

    target = HTML_DIR / f"{event_name}.html"
    HTML_DIR.mkdir(parents=True, exist_ok=True)
    content = Path(html_path).read_text(encoding="utf-8")
    final_path = safe_write(target, content)
    print(f"{event_name}: saved -> {final_path}")


def main():
    if not PROMPT_FILE.exists():
        raise SystemExit(f"Prompt file not found: {PROMPT_FILE}")

    with PROMPT_FILE.open(encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    for line in lines:
        if ":" not in line:
            continue
        name, prompt = line.split(":", 1)
        run_prompt(name.strip(), prompt.strip())


if __name__ == "__main__":
    main()

